#!/usr/bin/env node
var express = require('express')
  , Sequelize = require('sequelize');

/* MySQL stuff */
  /* Connecting */
  var sequelize = new Sequelize('in72k_aux3', 'root', null,
   { host: "localhost", port: 3306 });

  /* Defining the Schema for a Blog Post */
  var Post = sequelize.define('post', {
    id     : { type: Sequelize.INTEGER, autoIncrement: true },
    title  : { type: Sequelize.STRING, allowNull: false },
    body   : { type: Sequelize.TEXT, allowNull: false }
  });



/* app server */
  var app = express.createServer();

  app.use(express.static(__dirname + '/../../cliente'));

  /* use jade template engine */
  app.set('view engine', 'jade');
  app.set('view options');

  app.dynamicHelpers({ base: function() { return 'dynamic'; } });

  /* ROUTING: App Server */
    /* shows the blog index */
    app.get('/dynamic', function(req,res){
      Post.findAll().on('success', function(posts) {
        res.render('index', {base: 'dynamic', count: posts.length, posts: posts});
      });
    });

/* Everything's ok, let's listen */
app.listen(8124);
console.log('Server running at http://127.0.0.1:8124/');
console.log('Dynamic view at http://127.0.0.1:8124/dynamic/');